### ISSUE TITLE
Install help

### ISSUE THREAD

**Issue by likethesky** [evancz/airplane-mode#2]
So I opened the zip, dragged Airplane Mode into my Applications folder on Mac OS X Yosemite, but after I start it up, it asks for system password, then nothing.

I tried moving it back into the zip and opening it there, in case it needed some of the other cruft in there, but still no happy path.

Are there some other deps I need?  (It does look like my /etc/hosts file's been touched, but looks standard to me, just the usual in there.)

Thanks for Elm, btw!

**Comment by evancz** [comment]
Try clicking the thing again. It just toggles between two hosts files. The first one might be the typical one.

Nothing extra is needed. It's just a python script and it needs root to touch /etc/hosts

**Comment by likethesky** [comment]
So where do 'on' and 'off' need to live--in `/etc/` ? I don't see them 'installed' anywhere, maybe that's my problem, I need to create them myself?

**Comment by evancz** [comment]
It should all just be bundled. The .app should show up as an icon and you
click it. That's all there is to it. Each time you click and provide a
password, it'll toggle.

If you have messed with stuff, that probably isn't so good. It should "just
work"

I dont really want to provide "support" for this. I just made it for fun,
and posted it because some folks asked. Maybe there's something weird with
your OSX or something, and I don't think I can help if that's the case.

On Thursday, September 3, 2015, Bradford Cottel notifications@github.com
wrote:

> So where to 'on' and 'off' need to live--in /etc/ ? I don't see them
> 'installed' anywhere, maybe that's my problem, I need to create them myself?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/evancz/airplane-mode/issues/2#issuecomment-137562216.

## 

Sent from Gmail Mobile

**Comment by likethesky** [comment]
I got it working btw (a few months back). Today, I just discovered this free app too, so maybe some others might be interested as well: https://github.com/SelfControlApp/selfcontrol/ Thanks Evan!
